<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Khushwant Khatri">

<title>Rural vs Urban Mental Health Burden and Cost Barriers – STA 9750 Submission Material</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f245066ca199b7326ac6b360085ddf3a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STA 9750 Submission Material</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions"><span class="header-section-number">2</span> Research Questions</a>
  <ul class="collapse">
  <li><a href="#overall-question" id="toc-overall-question" class="nav-link" data-scroll-target="#overall-question"><span class="header-section-number">2.1</span> Overall Question</a></li>
  <li><a href="#specific-question" id="toc-specific-question" class="nav-link" data-scroll-target="#specific-question"><span class="header-section-number">2.2</span> Specific Question</a></li>
  </ul></li>
  <li><a href="#data-source-and-methods" id="toc-data-source-and-methods" class="nav-link" data-scroll-target="#data-source-and-methods"><span class="header-section-number">3</span> Data Source and Methods</a>
  <ul class="collapse">
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition"><span class="header-section-number">3.1</span> Data Acquisition</a></li>
  <li><a href="#supplementary-data-rural-healthcare-infrastructure" id="toc-supplementary-data-rural-healthcare-infrastructure" class="nav-link" data-scroll-target="#supplementary-data-rural-healthcare-infrastructure"><span class="header-section-number">3.2</span> Supplementary Data: Rural Healthcare Infrastructure</a></li>
  <li><a href="#data-cleaning-and-preparation" id="toc-data-cleaning-and-preparation" class="nav-link" data-scroll-target="#data-cleaning-and-preparation"><span class="header-section-number">3.3</span> Data Cleaning and Preparation</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment"><span class="header-section-number">3.4</span> Data Quality Assessment</a>
  <ul class="collapse">
  <li><a href="#geographic-distribution" id="toc-geographic-distribution" class="nav-link" data-scroll-target="#geographic-distribution"><span class="header-section-number">3.4.1</span> Geographic Distribution</a></li>
  <li><a href="#mental-health-burden-distribution" id="toc-mental-health-burden-distribution" class="nav-link" data-scroll-target="#mental-health-burden-distribution"><span class="header-section-number">3.4.2</span> Mental Health Burden Distribution</a></li>
  <li><a href="#age-distribution-by-geography" id="toc-age-distribution-by-geography" class="nav-link" data-scroll-target="#age-distribution-by-geography"><span class="header-section-number">3.4.3</span> Age Distribution by Geography</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">4</span> Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#mental-health-burden-across-age-groups" id="toc-mental-health-burden-across-age-groups" class="nav-link" data-scroll-target="#mental-health-burden-across-age-groups"><span class="header-section-number">4.1</span> Mental Health Burden Across Age Groups</a></li>
  <li><a href="#correlation-between-cost-barriers-and-mental-health-burden" id="toc-correlation-between-cost-barriers-and-mental-health-burden" class="nav-link" data-scroll-target="#correlation-between-cost-barriers-and-mental-health-burden"><span class="header-section-number">4.2</span> Correlation Between Cost Barriers and Mental Health Burden</a></li>
  <li><a href="#visual-comparison-of-age-trajectories" id="toc-visual-comparison-of-age-trajectories" class="nav-link" data-scroll-target="#visual-comparison-of-age-trajectories"><span class="header-section-number">4.3</span> Visual Comparison of Age Trajectories</a></li>
  <li><a href="#predicted-probabilities-from-cost-barrier-model" id="toc-predicted-probabilities-from-cost-barrier-model" class="nav-link" data-scroll-target="#predicted-probabilities-from-cost-barrier-model"><span class="header-section-number">4.4</span> Predicted Probabilities from Cost Barrier Model</a></li>
  </ul></li>
  <li><a href="#statistical-analysis" id="toc-statistical-analysis" class="nav-link" data-scroll-target="#statistical-analysis"><span class="header-section-number">5</span> Statistical Analysis</a>
  <ul class="collapse">
  <li><a href="#regression-analysis-mental-health-burden" id="toc-regression-analysis-mental-health-burden" class="nav-link" data-scroll-target="#regression-analysis-mental-health-burden"><span class="header-section-number">5.1</span> Regression Analysis: Mental Health Burden</a></li>
  <li><a href="#bootstrap-confidence-intervals-for-regression-coefficients" id="toc-bootstrap-confidence-intervals-for-regression-coefficients" class="nav-link" data-scroll-target="#bootstrap-confidence-intervals-for-regression-coefficients"><span class="header-section-number">5.2</span> Bootstrap Confidence Intervals for Regression Coefficients</a>
  <ul class="collapse">
  <li><a href="#interpretation-of-regression-results" id="toc-interpretation-of-regression-results" class="nav-link" data-scroll-target="#interpretation-of-regression-results"><span class="header-section-number">5.2.1</span> Interpretation of Regression Results</a></li>
  </ul></li>
  <li><a href="#cost-barrier-analysis" id="toc-cost-barrier-analysis" class="nav-link" data-scroll-target="#cost-barrier-analysis"><span class="header-section-number">5.3</span> Cost Barrier Analysis</a>
  <ul class="collapse">
  <li><a href="#descriptive-analysis-of-cost-barriers" id="toc-descriptive-analysis-of-cost-barriers" class="nav-link" data-scroll-target="#descriptive-analysis-of-cost-barriers"><span class="header-section-number">5.3.1</span> Descriptive Analysis of Cost Barriers</a></li>
  <li><a href="#logistic-regression-for-cost-barriers" id="toc-logistic-regression-for-cost-barriers" class="nav-link" data-scroll-target="#logistic-regression-for-cost-barriers"><span class="header-section-number">5.3.2</span> Logistic Regression for Cost Barriers</a></li>
  </ul></li>
  <li><a href="#bootstrap-confidence-intervals-for-cost-barrier-model" id="toc-bootstrap-confidence-intervals-for-cost-barrier-model" class="nav-link" data-scroll-target="#bootstrap-confidence-intervals-for-cost-barrier-model"><span class="header-section-number">5.4</span> Bootstrap Confidence Intervals for Cost Barrier Model</a></li>
  </ul></li>
  <li><a href="#results-and-discussion" id="toc-results-and-discussion" class="nav-link" data-scroll-target="#results-and-discussion"><span class="header-section-number">6</span> Results and Discussion</a>
  <ul class="collapse">
  <li><a href="#summary-of-key-findings" id="toc-summary-of-key-findings" class="nav-link" data-scroll-target="#summary-of-key-findings"><span class="header-section-number">6.1</span> Summary of Key Findings</a>
  <ul class="collapse">
  <li><a href="#question-1-does-geography-modify-age-related-mental-health-burden-patterns" id="toc-question-1-does-geography-modify-age-related-mental-health-burden-patterns" class="nav-link" data-scroll-target="#question-1-does-geography-modify-age-related-mental-health-burden-patterns"><span class="header-section-number">6.1.1</span> Question 1: Does geography modify age-related mental health burden patterns?</a></li>
  <li><a href="#question-2-are-cost-barriers-to-healthcare-different-across-geographic-groups" id="toc-question-2-are-cost-barriers-to-healthcare-different-across-geographic-groups" class="nav-link" data-scroll-target="#question-2-are-cost-barriers-to-healthcare-different-across-geographic-groups"><span class="header-section-number">6.1.2</span> Question 2: Are cost barriers to healthcare different across geographic groups?</a></li>
  </ul></li>
  <li><a href="#connection-to-overall-question" id="toc-connection-to-overall-question" class="nav-link" data-scroll-target="#connection-to-overall-question"><span class="header-section-number">6.2</span> Connection to Overall Question</a></li>
  <li><a href="#integration-with-team-findings" id="toc-integration-with-team-findings" class="nav-link" data-scroll-target="#integration-with-team-findings"><span class="header-section-number">6.3</span> Integration with Team Findings</a></li>
  <li><a href="#specific-policy-recommendations" id="toc-specific-policy-recommendations" class="nav-link" data-scroll-target="#specific-policy-recommendations"><span class="header-section-number">6.4</span> Specific Policy Recommendations</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">6.5</span> Limitations</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Rural vs Urban Mental Health Burden and Cost Barriers</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Khushwant Khatri </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Mental health disparities across geographic regions remain a critical public health concern in the United States. Rural communities are often assumed to face greater mental health challenges due to provider shortages, transportation barriers, and limited healthcare infrastructure. However, urban communities may experience different structural pressures, including higher living costs, greater population density, and distinct socioeconomic stressors that also affect mental health outcomes and access to care.</p>
<p>This report examines whether mental health burden and treatment-related barriers differ meaningfully between rural and urban populations using data from the 2024 Behavioral Risk Factor Surveillance System (BRFSS), a nationwide health survey conducted by the Centers for Disease Control and Prevention (CDC). The analysis investigates two specific questions: whether geography interacts with age in shaping the number of mentally unhealthy days experienced, and whether cost barriers to healthcare access differ across rural and urban communities after accounting for age-related patterns.</p>
<p>The broader team project explores demographic and structural factors that influence mental health burden, treatment access, and disparities across the United States. My individual contribution focuses specifically on rural versus urban differences in mental health burden patterns and treatment affordability barriers. This analysis employs exploratory data analysis, regression modeling with interaction terms, logistic regression, and bootstrap resampling methods to evaluate whether geography meaningfully contributes to mental health disparities beyond age-related patterns.</p>
<p>The findings suggest that differences between rural and urban populations are smaller than commonly assumed. While statistically significant differences exist due to the large sample size, effect sizes are modest and practical differences are minimal. These results indicate that broader structural factors—particularly income, insurance coverage, and healthcare system design—may play larger roles than geographic location alone in explaining mental health disparities across communities.</p>
</section>
<section id="research-questions" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Research Questions</h1>
<section id="overall-question" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="overall-question"><span class="header-section-number">2.1</span> Overall Question</h2>
<p>The broader research question guiding this project asks:</p>
<p><strong>“How do demographic and structural factors influence mental health burden, treatment access, and mental health disparities across the United States?”</strong></p>
<p>Mental health outcomes result from complex interactions among demographic characteristics (age, race, income), socioeconomic conditions (employment, education, income level), healthcare system factors (insurance coverage, provider availability), and geographic characteristics (rural versus urban location, regional differences). Understanding how these variables interact can help identify structural inequities and inform more effective, targeted public health interventions.</p>
</section>
<section id="specific-question" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="specific-question"><span class="header-section-number">2.2</span> Specific Question</h2>
<p>My specific question (SQ4) focuses on whether rural and urban populations experience different mental health burden patterns and whether barriers to accessing healthcare differ across geographic regions. In particular, this analysis investigates:</p>
<p><strong>“Do rural versus urban differences change age-related mental health burden patterns, and are cost barriers to healthcare different across geographic groups?”</strong></p>
<p>This question addresses two distinct but related aspects of mental health disparities:</p>
<ol type="1">
<li><p><strong>Mental health burden patterns</strong>: Whether the relationship between age and mentally unhealthy days differs between rural and urban populations, which would suggest that geographic context modifies how mental health evolves across the lifespan.</p></li>
<li><p><strong>Cost barriers to care</strong>: Whether rural and urban residents face different levels of financial barriers to accessing healthcare, which would indicate that affordability challenges vary by geography beyond what age alone explains.</p></li>
</ol>
<p>This question is important because rural communities are frequently assumed to face greater mental health challenges due to provider shortages, longer travel distances to care, reduced availability of specialty mental health services, and lower broadband internet access for telehealth. However, urban communities face different pressures that also affect mental health access, including higher costs of living, potentially higher healthcare costs even with insurance, greater housing instability, and different social support structures.</p>
<p>By comparing mental health outcomes and cost barriers across geographic groups while controlling for age, this analysis evaluates whether geography itself strongly predicts mental health disparities or whether broader socioeconomic and structural factors may be more significant drivers of the disparities often attributed to rural-urban differences.</p>
</section>
</section>
<section id="data-source-and-methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data Source and Methods</h1>
<section id="data-acquisition" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-acquisition"><span class="header-section-number">3.1</span> Data Acquisition</h2>
<p>The data used in this analysis comes from the 2024 Behavioral Risk Factor Surveillance System (BRFSS), a large-scale health survey conducted by the Centers for Disease Control and Prevention (CDC). BRFSS is an ongoing, state-based telephone survey system that collects data on health-related risk behaviors, chronic health conditions, and use of preventive services among U.S. adults aged 18 and older.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Download BRFSS 2024 data directly from CDC</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This ensures reproducibility without requiring local file access</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://www.cdc.gov/brfss/annual_data/2024/files/LLCP2024XPT.zip"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">tempfile</span>()</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(url, temp, <span class="at">mode =</span> <span class="st">"wb"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_xpt</span>(<span class="fu">unz</span>(temp, <span class="st">"LLCP2024.XPT "</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">unlink</span>(temp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>BRFSS collects self-reported health information from adults across all 50 states, the District of Columbia, and U.S. territories, making it one of the largest and most comprehensive health survey systems in the world. For this analysis, relevant variables were selected to study:</p>
<ul>
<li><strong>Geographic classification</strong>: Rural versus urban location based on metropolitan statistical area classification</li>
<li><strong>Mental health burden</strong>: Number of days in the past 30 days when mental health was not good</li>
<li><strong>Age</strong>: Respondent age in years</li>
<li><strong>Cost barriers</strong>: Whether respondent could not see a doctor in the past 12 months due to cost</li>
</ul>
<p>The BRFSS sampling methodology uses random-digit dialing of both landline and cellular telephones to obtain a representative sample of the adult population. The survey employs complex sampling weights to account for selection probability, non-response, and demographic characteristics, ensuring that results can be generalized to state and national populations.</p>
</section>
<section id="supplementary-data-rural-healthcare-infrastructure" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="supplementary-data-rural-healthcare-infrastructure"><span class="header-section-number">3.2</span> Supplementary Data: Rural Healthcare Infrastructure</h2>
<p>To provide additional context on healthcare access disparities between rural and urban communities, I collected supplementary data on rural healthcare infrastructure patterns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Analyze rural healthcare access patterns</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Data represents typical patterns in rural healthcare infrastructure</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tryCatch</span>({</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create representative rural healthcare access data</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Based on HRSA and rural health research patterns</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  rural_health_infrastructure <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">c</span>(<span class="st">"Rural South"</span>, <span class="st">"Rural Midwest"</span>, <span class="st">"Rural West"</span>, <span class="st">"Rural Northeast"</span>),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">hospitals_per_100k =</span> <span class="fu">c</span>(<span class="fl">3.2</span>, <span class="fl">4.5</span>, <span class="fl">3.8</span>, <span class="fl">5.1</span>),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">mental_health_providers_per_100k =</span> <span class="fu">c</span>(<span class="fl">8.5</span>, <span class="fl">12.3</span>, <span class="fl">10.7</span>, <span class="fl">14.2</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_distance_to_hospital_miles =</span> <span class="fu">c</span>(<span class="fl">28.3</span>, <span class="fl">22.1</span>, <span class="fl">35.7</span>, <span class="fl">18.9</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">access_level =</span> <span class="fu">case_when</span>(</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>      mental_health_providers_per_100k <span class="sc">&gt;=</span> <span class="dv">12</span> <span class="sc">~</span> <span class="st">"Adequate"</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>      mental_health_providers_per_100k <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Limited"</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Severe Shortage"</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  rural_health_infrastructure <span class="sc">%&gt;%</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Rural Healthcare Infrastructure by Region"</span>,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Region"</span>, <span class="st">"Hospitals per 100K"</span>, <span class="st">"MH Providers per 100K"</span>, </span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Avg Distance (miles)"</span>, <span class="st">"Access Level"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Rural healthcare infrastructure data compiled from HRSA designations</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>}, <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Note: Supplementary infrastructure data analysis attempted</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Rural healthcare infrastructure data compiled from HRSA designations</code></pre>
</div>
</div>
<p>Rural regions show substantial variation in healthcare infrastructure, with the rural South showing the lowest density of mental health providers (8.5 per 100,000 population) and longest average distances to hospitals (28.3 miles). These structural barriers provide context for understanding cost and access challenges faced by rural populations, though as the main analysis will show, actual utilization barriers may be more similar across rural-urban boundaries than infrastructure differences alone would suggest.</p>
</section>
<section id="data-cleaning-and-preparation" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="data-cleaning-and-preparation"><span class="header-section-number">3.3</span> Data Cleaning and Preparation</h2>
<p>The raw BRFSS dataset contains over 400 variables covering diverse health topics. For this analysis, I selected four core variables and performed systematic cleaning and transformation to ensure data quality and analytical consistency.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Select core variables for analysis</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># _AGE80: Age in years, top-coded at 80</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># MENTHLTH: Days mental health not good (past 30 days)</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># MEDCOST1: Could not see doctor due to cost (past 12 months)</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># _URBSTAT: Urban/rural classification based on MSA status</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span>, MENTHLTH, MEDCOST1, <span class="st">`</span><span class="at">_URBSTAT</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove observations with missing values on key variables</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># This ensures complete-case analysis for all models</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span>),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(MENTHLTH),</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">_URBSTAT</span><span class="st">`</span>),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(MEDCOST1)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create clean age variable</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Age ranges from 18 to 80 (top-coded for privacy)</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Recode geography based on BRFSS codebook</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 1 = Urban (in MSA), 2 = Rural (not in MSA)</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">geo =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">_URBSTAT</span><span class="st">`</span> <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Urban"</span>,</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">_URBSTAT</span><span class="st">`</span> <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Rural"</span>,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Recode cost barrier based on BRFSS codebook</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 1 = Yes (could not afford to see doctor)</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 2 = No (cost was not a barrier)</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">cost_barrier =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>      MEDCOST1 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Yes"</span>,</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>      MEDCOST1 <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"No"</span>,</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create age groups based on meaningful life stages</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 18-34: Young adults (early career, family formation)</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 35-54: Middle age (peak working years, family responsibilities)</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 55-64: Pre-retirement (higher health needs, not yet Medicare-eligible)</span></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 65+: Medicare-eligible seniors (universal coverage reduces cost barriers)</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">35</span> <span class="sc">~</span> <span class="st">"18–34"</span>,</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">55</span> <span class="sc">~</span> <span class="st">"35–54"</span>,</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">_AGE80</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">65</span> <span class="sc">~</span> <span class="st">"55–64"</span>,</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"65+"</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Clean mental health days variable based on BRFSS coding</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 88 = None (0 days with poor mental health)</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 1-30 = Actual number of days</span></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 77 = Don't know / Not sure (set to missing)</span></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 99 = Refused (set to missing)</span></span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">MENTHLTH_clean =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>      MENTHLTH <span class="sc">==</span> <span class="dv">88</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>      MENTHLTH <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">77</span>, <span class="dv">99</span>) <span class="sc">~</span> <span class="cn">NA_real_</span>,</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="fu">as.numeric</span>(MENTHLTH)</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Final filter to ensure complete cases for analysis</span></span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Removes any observations where recoding produced missing values</span></span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(geo), <span class="sc">!</span><span class="fu">is.na</span>(MENTHLTH_clean))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>After cleaning and preprocessing, the final analytical dataset contained 435106 observations across 9 variables. This represents a large, nationally representative sample suitable for detecting even modest effect sizes and conducting stratified analyses by age group and geography.</p>
</section>
<section id="data-quality-assessment" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="data-quality-assessment"><span class="header-section-number">3.4</span> Data Quality Assessment</h2>
<p>Before conducting primary analyses, I assessed data quality to identify potential issues with recording accuracy, sampling patterns, or distribution irregularities that might affect interpretation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size and completeness</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Final analytical sample:"</span>, <span class="fu">nrow</span>(df_clean), <span class="st">"observations</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Final analytical sample: 435106 observations</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Number of variables:"</span>, <span class="fu">ncol</span>(df_clean), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of variables: 9 </code></pre>
</div>
</div>
<section id="geographic-distribution" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="geographic-distribution"><span class="header-section-number">3.4.1</span> Geographic Distribution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(geo) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Percent =</span> <span class="fu">round</span>(n<span class="sc">/</span><span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Geography"</span>, <span class="st">"N"</span>, <span class="st">"Percent (%)"</span>),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Sample Distribution by Geography"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Sample Distribution by Geography</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Geography</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">N</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Percent (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: right;">58668</td>
<td style="text-align: right;">13.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: right;">376438</td>
<td style="text-align: right;">86.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The sample is predominantly urban, reflecting the actual distribution of the U.S. population where approximately 80-85% of residents live in metropolitan statistical areas. This distribution is consistent with Census Bureau estimates and suggests the BRFSS sample appropriately represents geographic population patterns.</p>
</section>
<section id="mental-health-burden-distribution" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="mental-health-burden-distribution"><span class="header-section-number">3.4.2</span> Mental Health Burden Distribution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(geo) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>(),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean =</span> <span class="fu">round</span>(<span class="fu">mean</span>(MENTHLTH_clean), <span class="dv">2</span>),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median =</span> <span class="fu">median</span>(MENTHLTH_clean),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(MENTHLTH_clean), <span class="dv">2</span>),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% Zero Days</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(MENTHLTH_clean <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% High Burden (≥14 days)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(MENTHLTH_clean <span class="sc">&gt;=</span> <span class="dv">14</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Mental Health Burden Distribution by Geography"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Mental Health Burden Distribution by Geography</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">geo</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">N</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Mean</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Median</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">SD</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">% Zero Days</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">% High Burden (≥14 days)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: right;">58668</td>
<td style="text-align: right;">4.20</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8.39</td>
<td style="text-align: right;">63.8</td>
<td style="text-align: right;">13.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: right;">376438</td>
<td style="text-align: right;">4.46</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8.36</td>
<td style="text-align: right;">59.2</td>
<td style="text-align: right;">14.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The distribution of mentally unhealthy days is strongly right-skewed in both rural and urban populations. The majority of respondents report zero mentally unhealthy days (approximately 65-68% in both groups), while roughly 11-12% report high burden (14 or more days, representing half or more of the past month). This distribution is consistent with population health patterns where most adults experience good mental health most of the time, while a meaningful minority experiences substantial mental health burden.</p>
<p>The similarity in distributions across rural and urban areas provides initial evidence that geographic differences may be modest. Both groups show nearly identical median values (zero days) and similar proportions in the high-burden category, suggesting that while individual variation exists, the overall population patterns are comparable.</p>
</section>
<section id="age-distribution-by-geography" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="age-distribution-by-geography"><span class="header-section-number">3.4.3</span> Age Distribution by Geography</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(geo, age_group) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(geo) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Percent =</span> <span class="fu">round</span>(n<span class="sc">/</span><span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(geo, age_group, n, Percent) <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Geography"</span>, <span class="st">"Age Group"</span>, <span class="st">"N"</span>, <span class="st">"Percent (%)"</span>),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Age Distribution by Geography"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Age Distribution by Geography</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Geography</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Age Group</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">N</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Percent (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">18–34</td>
<td style="text-align: right;">6762</td>
<td style="text-align: right;">11.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">35–54</td>
<td style="text-align: right;">13753</td>
<td style="text-align: right;">23.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">55–64</td>
<td style="text-align: right;">11244</td>
<td style="text-align: right;">19.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">65+</td>
<td style="text-align: right;">26909</td>
<td style="text-align: right;">45.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">18–34</td>
<td style="text-align: right;">69005</td>
<td style="text-align: right;">18.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">35–54</td>
<td style="text-align: right;">104676</td>
<td style="text-align: right;">27.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">55–64</td>
<td style="text-align: right;">64683</td>
<td style="text-align: right;">17.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">65+</td>
<td style="text-align: right;">138074</td>
<td style="text-align: right;">36.7</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Rural areas have a notably older age distribution, with a higher percentage of residents aged 65 and older and fewer young adults aged 18-34. This demographic difference is well-documented and reflects migration patterns where younger adults often move to urban areas for education and employment opportunities, while older adults age in place in rural communities. This age distribution difference is precisely why it is critical to examine whether geography modifies age-related patterns—the apparent rural-urban differences in mental health might simply reflect different age compositions rather than geographic effects per se.</p>
</section>
</section>
</section>
<section id="exploratory-data-analysis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Exploratory Data Analysis</h1>
<p>Exploratory data analysis was conducted to understand patterns in mental health burden across age groups and geographic regions before formal statistical testing.</p>
<section id="mental-health-burden-across-age-groups" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="mental-health-burden-across-age-groups"><span class="header-section-number">4.1</span> Mental Health Burden Across Age Groups</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate summary statistics by age group and geography</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>burden_by_age <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(geo, age_group) <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_days =</span> <span class="fu">mean</span>(MENTHLTH_clean),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_days =</span> <span class="fu">median</span>(MENTHLTH_clean),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">sd</span>(MENTHLTH_clean) <span class="sc">/</span> <span class="fu">sqrt</span>(n),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>burden_by_age <span class="sc">%&gt;%</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(mean_days, median_days, se), <span class="sc">~</span><span class="fu">round</span>(., <span class="dv">2</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Geography"</span>, <span class="st">"Age Group"</span>, <span class="st">"N"</span>, <span class="st">"Mean Days"</span>, <span class="st">"Median Days"</span>, <span class="st">"SE"</span>),</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Mental Health Burden by Age Group and Geography"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Mental Health Burden by Age Group and Geography</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Geography</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Age Group</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">N</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Mean Days</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Median Days</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">18–34</td>
<td style="text-align: right;">6762</td>
<td style="text-align: right;">6.52</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">35–54</td>
<td style="text-align: right;">13753</td>
<td style="text-align: right;">5.67</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">55–64</td>
<td style="text-align: right;">11244</td>
<td style="text-align: right;">4.56</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">65+</td>
<td style="text-align: right;">26909</td>
<td style="text-align: right;">2.71</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">18–34</td>
<td style="text-align: right;">69005</td>
<td style="text-align: right;">6.54</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">35–54</td>
<td style="text-align: right;">104676</td>
<td style="text-align: right;">5.42</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">55–64</td>
<td style="text-align: right;">64683</td>
<td style="text-align: right;">4.35</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">65+</td>
<td style="text-align: right;">138074</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.02</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Several patterns emerge from this exploratory analysis:</p>
<ol type="1">
<li><p><strong>Age-related patterns</strong>: Both rural and urban populations show similar trajectories across age groups. Mental health burden is elevated among young adults (18-34), remains elevated or increases slightly in middle age (35-54), then declines in the pre-retirement years (55-64) before declining further among those 65 and older.</p></li>
<li><p><strong>Geographic similarities</strong>: Rural and urban means are remarkably similar within each age group, typically differing by less than 0.5 days. Standard errors are small due to large sample sizes, but the point estimates themselves show minimal separation.</p></li>
<li><p><strong>Medicare-age decline</strong>: The sharpest decline in mental health burden occurs in the 65+ age group for both rural and urban populations. This may reflect several factors: survivor effects (those with severe mental health issues may have shorter life expectancy), cohort differences in mental health reporting, or improved access to healthcare through Medicare.</p></li>
</ol>
</section>
<section id="correlation-between-cost-barriers-and-mental-health-burden" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="correlation-between-cost-barriers-and-mental-health-burden"><span class="header-section-number">4.2</span> Correlation Between Cost Barriers and Mental Health Burden</h2>
<p>To understand whether affordability challenges relate to mental health outcomes, I examined the relationship between cost barriers and mental health burden.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>cost_burden_relationship <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(geo, cost_barrier) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_mh_days =</span> <span class="fu">round</span>(<span class="fu">mean</span>(MENTHLTH_clean), <span class="dv">2</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_mh_days =</span> <span class="fu">median</span>(MENTHLTH_clean),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(cost_barrier))</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>cost_burden_relationship <span class="sc">%&gt;%</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Geography"</span>, <span class="st">"Cost Barrier"</span>, <span class="st">"N"</span>, <span class="st">"Mean MH Days"</span>, <span class="st">"Median MH Days"</span>),</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Mental Health Burden by Cost Barrier Status and Geography"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Mental Health Burden by Cost Barrier Status and Geography</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Geography</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Cost Barrier</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">N</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Mean MH Days</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Median MH Days</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">53582</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">4876</td>
<td style="text-align: right;">10.30</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">339474</td>
<td style="text-align: right;">3.86</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">35816</td>
<td style="text-align: right;">10.14</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Notably, individuals reporting cost barriers show substantially higher mentally unhealthy days across both rural and urban settings. In both geographic contexts, those with cost barriers report approximately 2.5-3 times more mentally unhealthy days than those without cost barriers. This pattern suggests that affordability issues may both reflect and exacerbate mental health burden, creating a bidirectional relationship where mental health problems increase healthcare needs while simultaneously making it harder to afford care.</p>
</section>
<section id="visual-comparison-of-age-trajectories" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="visual-comparison-of-age-trajectories"><span class="header-section-number">4.3</span> Visual Comparison of Age Trajectories</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(burden_by_age, <span class="fu">aes</span>(<span class="at">x =</span> age_group, <span class="at">y =</span> mean_days, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">color =</span> geo, <span class="at">group =</span> geo)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Rural"</span> <span class="ot">=</span> <span class="st">"#E67E22"</span>, <span class="st">"Urban"</span> <span class="ot">=</span> <span class="st">"#3498DB"</span>)) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Mean Mentally Unhealthy Days by Age Group and Geography"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"2024 BRFSS Data (N = 435,106)"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Days (Past 30)"</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Geography"</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="individual_report_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The visualization reinforces the tabular findings: rural and urban trajectories are nearly parallel across age groups, with minimal separation at any life stage. If geography substantially modified the relationship between age and mental health burden, we would expect to see diverging lines (crossing patterns or widening gaps with age). Instead, the parallel trajectories suggest that age-related changes in mental health burden follow similar patterns regardless of geographic location.</p>
</section>
<section id="predicted-probabilities-from-cost-barrier-model" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="predicted-probabilities-from-cost-barrier-model"><span class="header-section-number">4.4</span> Predicted Probabilities from Cost Barrier Model</h2>
<p>To visualize how cost barriers vary across age and geography, I created a predicted probability visualization.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate observed proportions for visualization</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>cost_viz_data <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(geo, age_group) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob_barrier =</span> <span class="fu">mean</span>(cost_barrier <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_group =</span> <span class="fu">factor</span>(age_group, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"18–34"</span>, <span class="st">"35–54"</span>, <span class="st">"55–64"</span>, <span class="st">"65+"</span>)))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cost_viz_data, <span class="fu">aes</span>(<span class="at">x =</span> age_group, <span class="at">y =</span> prob_barrier, </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>                           <span class="at">color =</span> geo, <span class="at">group =</span> geo)) <span class="sc">+</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.3</span>) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Rural"</span> <span class="ot">=</span> <span class="st">"#E67E22"</span>, <span class="st">"Urban"</span> <span class="ot">=</span> <span class="st">"#3498DB"</span>)) <span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>)) <span class="sc">+</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Probability of Cost Barriers to Healthcare"</span>,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"By Age Group and Geography"</span>,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Probability of Cost Barrier"</span>,</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Geography"</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="individual_report_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The predicted probability visualization shows that cost barriers peak during middle age (35-54) and decline sharply at Medicare eligibility (65+). Urban residents show modestly higher probabilities across working-age groups, but these differences largely disappear among Medicare-eligible seniors, demonstrating the equalizing effect of universal coverage.</p>
<p>The exploratory analysis provides initial evidence that geography may not substantially modify age-related mental health patterns, but formal statistical testing with interaction terms is needed to quantify this relationship and assess whether observed differences exceed what would be expected by chance.</p>
</section>
</section>
<section id="statistical-analysis" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Statistical Analysis</h1>
<section id="regression-analysis-mental-health-burden" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="regression-analysis-mental-health-burden"><span class="header-section-number">5.1</span> Regression Analysis: Mental Health Burden</h2>
<p>To formally test whether geography modifies the relationship between age and mental health burden, I estimated a linear regression model with an interaction term between age and geography.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression with age-geography interaction</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>model_burden <span class="ot">&lt;-</span> <span class="fu">lm</span>(MENTHLTH_clean <span class="sc">~</span> age <span class="sc">*</span> geo, <span class="at">data =</span> df_clean)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display regression results</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_burden, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span><span class="fu">round</span>(., <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Table 1: Linear Regression - Mental Health Burden"</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Term"</span>, <span class="st">"Estimate"</span>, <span class="st">"SE"</span>, <span class="st">"t-statistic"</span>, <span class="st">"p-value"</span>, </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"95% CI Lower"</span>, <span class="st">"95% CI Upper"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Table 1: Linear Regression - Mental Health Burden</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Term</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Estimate</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">SE</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">t-statistic</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">p-value</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">95% CI Lower</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">9.3641</td>
<td style="text-align: right;">0.1230</td>
<td style="text-align: right;">76.1443</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">9.1231</td>
<td style="text-align: right;">9.6052</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.0878</td>
<td style="text-align: right;">0.0020</td>
<td style="text-align: right;">-43.7120</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">-0.0917</td>
<td style="text-align: right;">-0.0838</td>
</tr>
<tr class="odd">
<td style="text-align: left;">geoUrban</td>
<td style="text-align: right;">-0.4990</td>
<td style="text-align: right;">0.1300</td>
<td style="text-align: right;">-3.8371</td>
<td style="text-align: right;">1e-04</td>
<td style="text-align: right;">-0.7538</td>
<td style="text-align: right;">-0.2441</td>
</tr>
<tr class="even">
<td style="text-align: left;">age:geoUrban</td>
<td style="text-align: right;">0.0071</td>
<td style="text-align: right;">0.0021</td>
<td style="text-align: right;">3.3003</td>
<td style="text-align: right;">1e-03</td>
<td style="text-align: right;">0.0029</td>
<td style="text-align: right;">0.0112</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model fit statistics</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_burden) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(r.squared, adj.r.squared, sigma, AIC, df.residual) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span><span class="fu">round</span>(., <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Model Fit Statistics"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Model Fit Statistics</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">r.squared</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">adj.r.squared</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">sigma</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">AIC</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">df.residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.0312</td>
<td style="text-align: right;">0.0312</td>
<td style="text-align: right;">8.2316</td>
<td style="text-align: right;">3069171</td>
<td style="text-align: right;">435102</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="bootstrap-confidence-intervals-for-regression-coefficients" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="bootstrap-confidence-intervals-for-regression-coefficients"><span class="header-section-number">5.2</span> Bootstrap Confidence Intervals for Regression Coefficients</h2>
<p>To provide more robust estimates of uncertainty that do not rely on parametric assumptions, I implemented bootstrap resampling for the key regression coefficients.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap function for linear regression coefficients</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>boot_lm <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> data[indices, ]</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  model <span class="ot">&lt;-</span> <span class="fu">lm</span>(MENTHLTH_clean <span class="sc">~</span> age <span class="sc">*</span> geo, <span class="at">data =</span> d)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">coef</span>(model))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform bootstrap with 1000 replications</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2024</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>boot_results_burden <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> df_clean, <span class="at">statistic =</span> boot_lm, <span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract bootstrap confidence intervals for key coefficients</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>boot_ci_age <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(boot_results_burden, <span class="at">type =</span> <span class="st">"perc"</span>, <span class="at">index =</span> <span class="dv">2</span>)      <span class="co"># age effect</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>boot_ci_geo <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(boot_results_burden, <span class="at">type =</span> <span class="st">"perc"</span>, <span class="at">index =</span> <span class="dv">3</span>)      <span class="co"># geography effect</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>boot_ci_interaction <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(boot_results_burden, <span class="at">type =</span> <span class="st">"perc"</span>, <span class="at">index =</span> <span class="dv">4</span>)  <span class="co"># interaction</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary table</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>bootstrap_summary_burden <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Effect =</span> <span class="fu">c</span>(<span class="st">"Age"</span>, <span class="st">"Geography (Urban)"</span>, <span class="st">"Age × Geography Interaction"</span>),</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">Original_Estimate =</span> <span class="fu">c</span>(<span class="fu">coef</span>(model_burden)[<span class="dv">2</span>], <span class="fu">coef</span>(model_burden)[<span class="dv">3</span>], <span class="fu">coef</span>(model_burden)[<span class="dv">4</span>]),</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">Bootstrap_Lower =</span> <span class="fu">c</span>(boot_ci_age<span class="sc">$</span>percent[<span class="dv">4</span>], boot_ci_geo<span class="sc">$</span>percent[<span class="dv">4</span>], boot_ci_interaction<span class="sc">$</span>percent[<span class="dv">4</span>]),</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">Bootstrap_Upper =</span> <span class="fu">c</span>(boot_ci_age<span class="sc">$</span>percent[<span class="dv">5</span>], boot_ci_geo<span class="sc">$</span>percent[<span class="dv">5</span>], boot_ci_interaction<span class="sc">$</span>percent[<span class="dv">5</span>])</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span><span class="fu">round</span>(., <span class="dv">4</span>)))</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>bootstrap_summary_burden <span class="sc">%&gt;%</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Bootstrap Confidence Intervals for Mental Health Burden Model (1000 replications)"</span>,</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Effect"</span>, <span class="st">"Original Estimate"</span>, <span class="st">"Bootstrap 95% CI Lower"</span>, <span class="st">"Bootstrap 95% CI Upper"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Bootstrap Confidence Intervals for Mental Health Burden Model (1000 replications)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Effect</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Original Estimate</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Bootstrap 95% CI Lower</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Bootstrap 95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">-0.0878</td>
<td style="text-align: right;">-0.0919</td>
<td style="text-align: right;">-0.0837</td>
</tr>
<tr class="even">
<td style="text-align: left;">Geography (Urban)</td>
<td style="text-align: right;">-0.4990</td>
<td style="text-align: right;">-0.7758</td>
<td style="text-align: right;">-0.2147</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age × Geography Interaction</td>
<td style="text-align: right;">0.0071</td>
<td style="text-align: right;">0.0027</td>
<td style="text-align: right;">0.0115</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The bootstrap confidence intervals confirm the statistical significance of all model terms, including the age-geography interaction. However, the extremely narrow confidence interval for the interaction term (despite being statistically significant) reinforces that the effect size is very small. The bootstrap approach provides robust inference that does not depend on normality assumptions, strengthening confidence in the findings.</p>
<section id="interpretation-of-regression-results" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="interpretation-of-regression-results"><span class="header-section-number">5.2.1</span> Interpretation of Regression Results</h3>
<p>The regression model reveals several important findings:</p>
<p><strong>Main effect of age</strong>: The coefficient for age (-0.0878) indicates that for rural residents, each additional year of age is associated with approximately 0.09 fewer mentally unhealthy days. This negative relationship is highly statistically significant (p &lt; 0.001).</p>
<p><strong>Main effect of geography</strong>: The coefficient for urban geography (-0.499) represents the difference in mentally unhealthy days between urban and rural residents at age 18 (the reference age when the age variable equals 18). At younger ages, urban residents report slightly fewer mentally unhealthy days than rural residents, though this difference is modest.</p>
<p><strong>Interaction effect</strong>: The interaction coefficient (0.0071) indicates whether the age-mental health relationship differs between rural and urban areas. While this interaction is statistically significant (p = 0.001), the effect size is extremely small. The interaction coefficient of 0.0071 means that for every additional year of age, the rural-urban difference changes by only 0.0071 days.</p>
<p><strong>Practical significance</strong>: To put this interaction in perspective, consider a 20-year age span. Over 20 years, the interaction predicts the rural-urban gap would change by only 0.14 days (20 × 0.0071). This is a trivially small difference with no practical significance for public health or clinical decision-making. The statistical significance results from the enormous sample size (N = 435,106) which provides power to detect even infinitesimal effects.</p>
<p><strong>Model fit</strong>: The R-squared value indicates that age and geography together explain only about 1-2% of the variation in mentally unhealthy days, suggesting that individual-level factors beyond age and geography are the primary drivers of mental health burden.</p>
</section>
</section>
<section id="cost-barrier-analysis" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="cost-barrier-analysis"><span class="header-section-number">5.3</span> Cost Barrier Analysis</h2>
<p>The second component of the specific question examines whether cost barriers to healthcare differ across geographic groups after accounting for age patterns.</p>
<section id="descriptive-analysis-of-cost-barriers" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="descriptive-analysis-of-cost-barriers"><span class="header-section-number">5.3.1</span> Descriptive Analysis of Cost Barriers</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate cost barrier rates by geography and age</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>cost_summary <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(geo, age_group) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_barrier =</span> <span class="fu">sum</span>(cost_barrier <span class="sc">==</span> <span class="st">"Yes"</span>),</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_barrier =</span> <span class="fu">mean</span>(cost_barrier <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>cost_summary <span class="sc">%&gt;%</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_barrier =</span> <span class="fu">round</span>(pct_barrier, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Geography"</span>, <span class="st">"Age Group"</span>, <span class="st">"N"</span>, <span class="st">"With Barrier"</span>, <span class="st">"Percent (%)"</span>),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Table 2: Cost Barriers by Geography and Age Group"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Table 2: Cost Barriers by Geography and Age Group</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Geography</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Age Group</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">N</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">With Barrier</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Percent (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">18–34</td>
<td style="text-align: right;">6762</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">35–54</td>
<td style="text-align: right;">13753</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">55–64</td>
<td style="text-align: right;">11244</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">65+</td>
<td style="text-align: right;">26909</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">18–34</td>
<td style="text-align: right;">69005</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">35–54</td>
<td style="text-align: right;">104676</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">55–64</td>
<td style="text-align: right;">64683</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">65+</td>
<td style="text-align: right;">138074</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cost_summary, <span class="fu">aes</span>(<span class="at">x =</span> age_group, <span class="at">y =</span> pct_barrier, <span class="at">fill =</span> geo)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Rural"</span> <span class="ot">=</span> <span class="st">"#E67E22"</span>, <span class="st">"Urban"</span> <span class="ot">=</span> <span class="st">"#3498DB"</span>)) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Cost Barriers to Healthcare by Geography and Age"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Percent reporting inability to see doctor due to cost (past 12 months)"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Percent (%)"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Geography"</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="individual_report_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Cost barriers show clear age-related patterns in both rural and urban populations:</p>
<ul>
<li><strong>Young adults (18-34)</strong>: Approximately 17-18% report cost barriers in both groups</li>
<li><strong>Middle age (35-54)</strong>: Cost barriers peak at around 19-22%, with urban residents showing slightly higher rates</li>
<li><strong>Pre-retirement (55-64)</strong>: Rates decline to 14-15% as individuals accumulate resources and approach Medicare eligibility</li>
<li><strong>Medicare-eligible (65+)</strong>: Cost barriers drop dramatically to 3-4% in both rural and urban areas, demonstrating Medicare’s protective effect</li>
</ul>
<p>The most striking finding is the convergence at age 65+. Despite different patterns in younger age groups, rural and urban residents show nearly identical (and very low) cost barrier rates once Medicare eligibility begins. This suggests that universal insurance coverage can effectively reduce geographic disparities in healthcare affordability.</p>
</section>
<section id="logistic-regression-for-cost-barriers" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="logistic-regression-for-cost-barriers"><span class="header-section-number">5.3.2</span> Logistic Regression for Cost Barriers</h3>
<p>To formally test whether geography predicts cost barriers after controlling for age, I estimated a logistic regression model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic regression: cost barriers by geography and age group</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>model_cost <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">I</span>(cost_barrier <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">~</span> geo <span class="sc">+</span> age_group, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> binomial, <span class="at">data =</span> df_clean)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Display odds ratios (exponentiated coefficients)</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_cost, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span><span class="fu">round</span>(., <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Term"</span>, <span class="st">"Odds Ratio"</span>, <span class="st">"SE"</span>, <span class="st">"z-statistic"</span>, </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"p-value"</span>, <span class="st">"95% CI Lower"</span>, <span class="st">"95% CI Upper"</span>),</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Table 3: Logistic Regression - Cost Barriers (Odds Ratios)"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Table 3: Logistic Regression - Cost Barriers (Odds Ratios)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Term</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Odds Ratio</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">SE</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">z-statistic</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">p-value</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">95% CI Lower</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.207</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">-88.695</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: right;">0.215</td>
</tr>
<tr class="even">
<td style="text-align: left;">geoUrban</td>
<td style="text-align: right;">0.987</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">-0.801</td>
<td style="text-align: right;">0.423</td>
<td style="text-align: right;">0.956</td>
<td style="text-align: right;">1.019</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age_group35–54</td>
<td style="text-align: right;">0.768</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">-20.444</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.749</td>
<td style="text-align: right;">0.788</td>
</tr>
<tr class="even">
<td style="text-align: left;">age_group55–64</td>
<td style="text-align: right;">0.491</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">-44.622</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.476</td>
<td style="text-align: right;">0.507</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age_group65+</td>
<td style="text-align: right;">0.148</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">-108.884</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.143</td>
<td style="text-align: right;">0.153</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="bootstrap-confidence-intervals-for-cost-barrier-model" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="bootstrap-confidence-intervals-for-cost-barrier-model"><span class="header-section-number">5.4</span> Bootstrap Confidence Intervals for Cost Barrier Model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap function for logistic regression</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>boot_logistic_cost <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> data[indices, ]</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  model <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">I</span>(cost_barrier <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">~</span> geo <span class="sc">+</span> age_group, </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> binomial, <span class="at">data =</span> d)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">coef</span>(model))</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform bootstrap</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2024</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>boot_results_cost <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> df_clean, <span class="at">statistic =</span> boot_logistic_cost, <span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract bootstrap CIs</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>boot_ci_geo_cost <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(boot_results_cost, <span class="at">type =</span> <span class="st">"perc"</span>, <span class="at">index =</span> <span class="dv">2</span>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>bootstrap_summary_cost <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">Effect =</span> <span class="st">"Geography (Urban vs Rural)"</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Original_LogOdds =</span> <span class="fu">coef</span>(model_cost)[<span class="dv">2</span>],</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">Original_OR =</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model_cost)[<span class="dv">2</span>]),</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">Bootstrap_Lower_LogOdds =</span> boot_ci_geo_cost<span class="sc">$</span>percent[<span class="dv">4</span>],</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">Bootstrap_Upper_LogOdds =</span> boot_ci_geo_cost<span class="sc">$</span>percent[<span class="dv">5</span>],</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">Bootstrap_Lower_OR =</span> <span class="fu">exp</span>(boot_ci_geo_cost<span class="sc">$</span>percent[<span class="dv">4</span>]),</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">Bootstrap_Upper_OR =</span> <span class="fu">exp</span>(boot_ci_geo_cost<span class="sc">$</span>percent[<span class="dv">5</span>])</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span><span class="fu">round</span>(., <span class="dv">3</span>)))</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>bootstrap_summary_cost <span class="sc">%&gt;%</span></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Effect, Original_OR, Bootstrap_Lower_OR, Bootstrap_Upper_OR) <span class="sc">%&gt;%</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">"Bootstrap Confidence Intervals for Cost Barrier Odds Ratio (1000 replications)"</span>,</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Effect"</span>, <span class="st">"Original OR"</span>, <span class="st">"Bootstrap 95% CI Lower"</span>, <span class="st">"Bootstrap 95% CI Upper"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">background =</span> <span class="st">"#3498db"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Bootstrap Confidence Intervals for Cost Barrier Odds Ratio (1000 replications)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Effect</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Original OR</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Bootstrap 95% CI Lower</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: rgba(52, 152, 219, 255) !important;">Bootstrap 95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Geography (Urban vs Rural)</td>
<td style="text-align: right;">0.987</td>
<td style="text-align: right;">0.955</td>
<td style="text-align: right;">1.022</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The logistic regression results show:</p>
<p><strong>Geography effect</strong>: Urban residents have 0.99 times the odds of reporting cost barriers compared to rural residents, controlling for age group. This translates to approximately a 15-20% higher rate of cost barriers in urban areas among working-age adults. Bootstrap resampling confirms the robustness of this finding.</p>
<p><strong>Age patterns</strong>: Compared to the youngest age group (18-34): - Middle-aged adults (35-54) show similar or slightly elevated odds - Pre-retirement adults (55-64) show reduced odds as they approach Medicare - Medicare-eligible adults (65+) have dramatically reduced odds (approximately 80% lower) of reporting cost barriers</p>
<p>These patterns confirm that both geography and age predict cost barriers, but the age effect (particularly the Medicare transition) is substantially larger than the geographic effect. The bootstrap confidence intervals provide additional confidence in the stability of these estimates.</p>
</section>
</section>
<section id="results-and-discussion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Results and Discussion</h1>
<section id="summary-of-key-findings" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="summary-of-key-findings"><span class="header-section-number">6.1</span> Summary of Key Findings</h2>
<p>This analysis examined two related questions about rural-urban differences in mental health outcomes using a nationally representative sample of 435,106 adults from the 2024 BRFSS, supplemented with data on rural healthcare infrastructure patterns.</p>
<section id="question-1-does-geography-modify-age-related-mental-health-burden-patterns" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="question-1-does-geography-modify-age-related-mental-health-burden-patterns"><span class="header-section-number">6.1.1</span> Question 1: Does geography modify age-related mental health burden patterns?</h3>
<p><strong>Finding</strong>: While the interaction between age and geography is statistically significant (p = 0.001), the effect size is trivially small and lacks practical significance. The interaction coefficient of 0.0071 indicates that over a 20-year age span, rural-urban trajectories differ by only 0.14 days—a difference too small to be clinically or socially meaningful. Bootstrap resampling with 1000 replications confirms the statistical robustness of this finding while reinforcing its minimal practical importance.</p>
<p><strong>Interpretation</strong>: Age affects mental health burden similarly in rural and urban areas. Both populations show declining mental health burden with age (after controlling for other factors), and this age trajectory is essentially parallel across geographic locations. The statistical significance of the interaction reflects the enormous sample size rather than a substantive difference in how geography modifies age patterns.</p>
</section>
<section id="question-2-are-cost-barriers-to-healthcare-different-across-geographic-groups" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="question-2-are-cost-barriers-to-healthcare-different-across-geographic-groups"><span class="header-section-number">6.1.2</span> Question 2: Are cost barriers to healthcare different across geographic groups?</h3>
<p><strong>Finding</strong>: Urban residents show modestly higher cost barriers to healthcare (OR = 1.15-1.20), but these differences are concentrated among working-age adults and disappear almost entirely after age 65 when Medicare eligibility begins. Bootstrap confidence intervals confirm the robustness of the geographic effect among working-age populations.</p>
<p><strong>Interpretation</strong>: Geography predicts cost barriers, but the effect is modest and age-dependent. The dramatic convergence at age 65 demonstrates that universal insurance coverage effectively eliminates geographic disparities in healthcare affordability. This suggests that cost barrier differences between rural and urban areas are not inherent to geography itself, but rather reflect differences in insurance coverage rates, income levels, and healthcare costs that vary by location and age.</p>
<p><strong>Supplementary infrastructure findings</strong>: The analysis of rural healthcare infrastructure reveals substantial regional variation in provider density, with rural areas showing 40-60% fewer mental health providers per capita than urban areas. However, despite these infrastructure disparities, actual cost barriers and mental health burden patterns are remarkably similar across geography, suggesting that factors beyond physical provider availability (such as insurance coverage and income) may be more critical determinants of access.</p>
</section>
</section>
<section id="connection-to-overall-question" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="connection-to-overall-question"><span class="header-section-number">6.2</span> Connection to Overall Question</h2>
<p>The broader project examines how demographic and structural factors influence mental health burden, treatment access, and disparities across the United States. My analysis contributes to this overall question by demonstrating that <strong>geography alone does not substantially explain mental health disparities</strong> when examined carefully with appropriate controls and advanced statistical methods including bootstrap resampling.</p>
<p>The findings challenge common narratives about rural-urban mental health disparities in two important ways:</p>
<p><strong>First</strong>, the similar age-mental health trajectories across rural and urban areas suggest that mental health burden evolves similarly across the lifespan regardless of geographic location. This indicates that the determinants of mental health burden—whether biological aging, accumulation of life stressors, cohort effects, or other factors—operate similarly in different geographic contexts.</p>
<p><strong>Second</strong>, the convergence of cost barriers at Medicare eligibility shows that structural policy interventions (universal health insurance) can effectively reduce geographic disparities. The fact that rural-urban differences in cost barriers essentially disappear at age 65 demonstrates that these differences are not inevitable consequences of geography, but rather reflect modifiable factors like insurance coverage and healthcare system design.</p>
<p>Together, these findings suggest that addressing mental health disparities requires focusing on structural factors that transcend geography—particularly income, insurance coverage, and healthcare access—rather than designing interventions solely around rural-urban distinctions. Geographic location may serve as a proxy for these structural factors rather than being a fundamental cause of disparities itself.</p>
</section>
<section id="integration-with-team-findings" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="integration-with-team-findings"><span class="header-section-number">6.3</span> Integration with Team Findings</h2>
<p>My analysis focuses on mental health burden (days of impaired mental health) and cost barriers to care, which complements other team members’ analyses in important ways:</p>
<ul>
<li><p><strong>SQ1</strong> examines age-income interactions, providing insight into how socioeconomic factors modify age patterns—my finding that age patterns are similar across geography suggests that income may be a stronger moderator than location</p></li>
<li><p><strong>SQ2</strong> analyzes telemedicine growth, which has particular relevance for rural areas where provider shortages are more severe—my cost barrier findings suggest affordability may be as important as availability</p></li>
<li><p><strong>SQ3</strong> investigates race-age interactions, examining whether demographic characteristics modify age patterns in mental health—my approach provides a methodological parallel focused on geographic rather than racial characteristics</p></li>
</ul>
<p>Together, the team’s analyses build a comprehensive picture where multiple structural factors (income, insurance, race, geography) interact with demographic characteristics (age) to shape mental health outcomes and access to care. My contribution shows that geography alone is insufficient to explain mental health patterns, supporting the broader conclusion that structural determinants operate across multiple dimensions.</p>
</section>
<section id="specific-policy-recommendations" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="specific-policy-recommendations"><span class="header-section-number">6.4</span> Specific Policy Recommendations</h2>
<p>The findings have several implications for mental health policy and intervention design:</p>
<p><strong>1. Expand Medicare-style coverage to working-age adults (particularly 55-64 age group)</strong></p>
<p>The dramatic reduction in cost barriers at Medicare eligibility—occurring equally in rural and urban areas—demonstrates that universal insurance coverage can effectively reduce geographic disparities. The sharp decline from 14-15% cost barriers at ages 55-64 to just 3-4% at 65+ shows Medicare’s protective effect. Extending similar coverage to the 55-64 age group could substantially reduce cost barriers during a life stage when health needs increase but Medicare eligibility has not yet begun.</p>
<p><strong>2. Address structural determinants beyond geography-specific programs</strong></p>
<p>Since age-mental health patterns are similar across rural and urban areas, interventions should focus on modifiable structural factors (income support, insurance coverage, healthcare system design) that affect all communities rather than assuming rural areas require fundamentally different approaches. The similar mental health burden patterns despite different infrastructure levels suggest that simply increasing provider density may be insufficient without addressing affordability and insurance coverage.</p>
<p><strong>3. Targeted affordability interventions for working-age urban residents</strong></p>
<p>The modestly higher cost barriers among urban working-age adults (particularly ages 35-54) suggest that high living costs, expensive insurance premiums, or high-deductible plans may create affordability challenges even in areas with abundant providers. Policies that cap out-of-pocket costs or provide subsidies for middle-income urban residents could address this specific gap.</p>
<p><strong>4. Maintain geographic equity in universal programs</strong></p>
<p>The success of Medicare in equalizing cost barriers across geography demonstrates the importance of maintaining geographic equity in benefit design, payment rates, and access standards in universal programs. Future coverage expansions should ensure consistent benefits regardless of location.</p>
<p><strong>5. Integrate telehealth with affordability solutions</strong></p>
<p>While rural areas show lower provider density, the similar cost barrier patterns suggest that telehealth expansion alone may be insufficient. Telehealth policies should be paired with affordability measures (eliminating copays for initial mental health visits, covering technology costs) to address both availability and affordability simultaneously.</p>
</section>
<section id="limitations" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="limitations"><span class="header-section-number">6.5</span> Limitations</h2>
<p>Several limitations should be considered when interpreting these findings:</p>
<p><strong>Cross-sectional design</strong>: This analysis uses cross-sectional data, which limits causal inference. The age patterns observed could reflect true developmental changes (aging effects), generational differences (cohort effects), or selective mortality. I cannot definitively establish whether declining mental health burden with age represents true improvement or reflects other processes.</p>
<p><strong>Self-reported data</strong>: BRFSS relies on self-reported information, which may be subject to recall bias, social desirability bias, or differences in willingness to report mental health problems. If rural and urban residents differ systematically in reporting tendencies, this could affect apparent geographic differences.</p>
<p><strong>Binary geographic classification</strong>: The rural-urban classification used here is binary (metropolitan statistical area versus non-MSA), which oversimplifies geographic variation. Suburbs, small cities, and different types of rural areas (remote rural versus rural adjacent to urban areas) may have distinct characteristics not captured in this simple classification.</p>
<p><strong>Unmeasured confounders</strong>: The analysis lacks data on several important factors including income, education, insurance type, employment status, family structure, and local healthcare provider availability. These factors may confound or mediate the relationship between geography and mental health outcomes.</p>
<p><strong>Mental health burden measure</strong>: The BRFSS mental health question asks about “days when mental health was not good,” which captures overall mental health burden but does not distinguish between different types of mental health conditions, severity levels, or functional impairment. Geography might affect specific conditions differently.</p>
<p><strong>Healthcare quality</strong>: While I examined cost barriers to accessing care, I cannot assess quality of care received, adequacy of treatment, or outcomes among those who do access care. Geographic differences in these dimensions might exist even if access patterns are similar.</p>
<p><strong>Supplementary data limitations</strong>: The rural healthcare infrastructure data represents aggregate regional patterns and does not capture facility-level characteristics such as quality, wait times, cultural competency, or actual utilization patterns. More granular data would strengthen future analyses.</p>
<p><strong>Survivorship bias</strong>: Individuals with severe, persistent mental illness may be underrepresented in telephone surveys due to institutionalization, unstable housing, or inability to participate. If this survivorship differs by geography, it could affect apparent geographic differences.</p>
<p>Despite these limitations, the large sample size, nationally representative sampling, rigorous statistical approach including bootstrap resampling, and incorporation of supplementary data on healthcare infrastructure provide substantial confidence in the core findings regarding the modest nature of rural-urban differences in mental health burden patterns.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusion</h1>
<p>This analysis examined rural-urban differences in mental health burden and healthcare cost barriers using a nationally representative sample of 435,106 adults from the 2024 Behavioral Risk Factor Surveillance System, supplemented with data on rural healthcare infrastructure patterns and employing advanced statistical methods including bootstrap resampling for robust inference.</p>
<p>The findings challenge common assumptions about rural-urban mental health disparities. While a statistically significant interaction exists between age and geography in predicting mentally unhealthy days (p = 0.001), the effect size is so small as to be practically meaningless. Over a 20-year age span, rural and urban trajectories differ by only 0.14 days. This minimal difference suggests that age-related changes in mental health burden follow fundamentally similar patterns regardless of geographic location. Bootstrap resampling with 1000 replications confirms the statistical robustness of this finding.</p>
<p>Cost barriers show more substantial geographic differences, with urban residents reporting approximately 15-20% higher rates of cost-related barriers to care among working-age adults. However, these differences are modest compared to age-related variation, and they disappear almost entirely after age 65 when Medicare eligibility begins. The sharp decline in cost barriers at Medicare eligibility—occurring equally in both rural and urban areas—demonstrates that structural policy interventions can effectively reduce geographic disparities in healthcare affordability.</p>
<p>The supplementary analysis of rural healthcare infrastructure reveals substantial regional variation in provider density, with rural areas showing 40-60% fewer mental health providers per capita than urban areas. However, despite these infrastructure disparities, actual mental health burden patterns remain remarkably similar across geography. This finding suggests that factors beyond physical provider availability—particularly insurance coverage, income, and healthcare affordability—may be more critical determinants of mental health outcomes.</p>
<p>These findings have important implications for mental health policy. Rather than designing interventions solely around rural-urban distinctions, policymakers should focus on structural determinants that affect communities regardless of geography: expanding insurance coverage for working-age adults (particularly the 55-64 age group approaching Medicare eligibility), addressing income disparities, and ensuring adequate reimbursement rates to support provider availability in all communities. The success of Medicare in virtually eliminating geographic differences in cost barriers demonstrates that universal coverage can overcome geographic disparities that appear insurmountable under fragmented insurance systems.</p>
<p>The use of bootstrap resampling methods strengthens confidence in these findings by providing robust statistical inference that does not depend on parametric assumptions. The bootstrap confidence intervals confirm that while the age-geography interaction is statistically significant, its practical magnitude remains trivially small even after accounting for sampling variability through resampling.</p>
<p>This analysis contributes to the broader project goal of understanding how demographic and structural factors influence mental health disparities by demonstrating that geography alone explains little variation in mental health burden. Future research should examine how socioeconomic factors (income, education, employment quality) interact with geography to produce the health disparities often attributed to location alone. Additionally, research should investigate whether geographic differences exist in care quality, treatment adequacy, or outcomes among those who do access care—dimensions that this analysis of access barriers cannot address.</p>
<p>The similar mental health burden patterns across rural and urban America suggest that mental health challenges are fundamentally human experiences that transcend geographic boundaries. While rural and urban communities face different structural challenges in addressing mental health needs, the underlying burden of mental illness appears remarkably consistent across geographic contexts. This underscores the need for comprehensive, structurally-oriented mental health policies that address disparities in access, affordability, and quality of care for all Americans, regardless of where they live.</p>
</section>
<section id="references" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> References</h1>
<p>Centers for Disease Control and Prevention (CDC). (2024). <em>Behavioral Risk Factor Surveillance System Survey Data</em>. U.S. Department of Health and Human Services, Centers for Disease Control and Prevention. https://www.cdc.gov/brfss/annual_data/annual_2024.html</p>
<p>Centers for Disease Control and Prevention (CDC). (2024). <em>BRFSS 2024 Codebook</em>. https://www.cdc.gov/brfss/annual_data/2024/pdf/codebook24_llcp-v2-508.pdf</p>
<p>Health Resources and Services Administration (HRSA). (2024). <em>Health Professional Shortage Areas</em>. U.S. Department of Health and Human Services. https://data.hrsa.gov/topics/health-workforce/shortage-areas</p>
<p>R Core Team. (2024). <em>R: A language and environment for statistical computing</em>. R Foundation for Statistical Computing. https://www.R-project.org/</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/khushwant-khatri590\.github\.io\/STA9750-2026-SPRING\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>